### ISSUE TITLE
ollama provider: runtime error

### ISSUE THREAD

**Issue by kushtrimjunuzi** [meysamhadeli/codai#49]
config.yml
```
user@m codaitestrepo % cat config.yml 
ai_provider_config:
  provider_name: "ollama"
  chat_completion_url: "http://localhost:11434/v1/chat/completions"
  chat_completion_model: "deepseek-coder-v2"
  embedding_url: "http://localhost:11434/v1/embeddings"
  embedding_model: "nomic-embed-text"
  temperature: 0.2
  stream: true
  encoding_format: "float"
  threshold: 0
theme: "dracula"
RAG: true
```

running cmd in macos (go version go1.22.8 darwin/arm64):
codai compiled from commit 07839e7d4b7f65809b19cf7ae35e227962a66660
```
user@m codaitestrepo % ./codai code  
⠙ Loading Context... (0s)
> test
⠦ Embedding Context... (0s)panic: runtime error: index out of range [0] with length 0

goroutine 66 [running]:
github.com/meysamhadeli/codai/cmd.handleCodeCommand.func1.1.1()
        /Users/user/myprojects/codaitestrepo/cmd/code.go:105 +0xbc
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer.Operation.withEmptyData.func1()
        /Users/user/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:18 +0x24
github.com/cenkalti/backoff/v4.doRetryNotify[...](0x14003709e78?, {0x105e1f0f0, 0x14000020540}, 0x0, {0x0, 0x0?})
        /Users/user/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:88 +0xcc
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0x0?, {0x105e1f0f0?, 0x14000020540?}, 0xcf1f82fd81c4d459?, {0x0?, 0x0?})
        /Users/user/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:61 +0x5c
github.com/cenkalti/backoff/v4.RetryNotify(...)
        /Users/user/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:49
github.com/cenkalti/backoff/v4.Retry(...)
        /Users/user/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:38
github.com/meysamhadeli/codai/utils.RetryWithBackoff(0x1400350bf10, 0x3)
        /Users/user/myprojects/codaitestrepo/utils/retry_backoff.go:20 +0xbc
github.com/meysamhadeli/codai/cmd.handleCodeCommand.func1.1({{0x1400002cb69, 0x27}, {0x1400012d080, 0x14e}, {0x1400054e620, 0x6e}})
        /Users/user/myprojects/codaitestrepo/cmd/code.go:110 +0xc8
created by github.com/meysamhadeli/codai/cmd.handleCodeCommand.func1 in goroutine 20
        /Users/user/myprojects/codaitestrepo/cmd/code.go:96 +0xe20
```
    
    
ollama server logs (ollama version v0.4.1):
```
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
time=2024-11-08T20:21:33.675-05:00 level=ERROR source=routes.go:453 msg="embedding generation failed" error="context canceled"
[GIN] 2024/11/08 - 20:21:33 | 500 |   81.519291ms |       127.0.0.1 | POST     "/v1/embeddings"
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
time=2024-11-08T20:21:33.675-05:00 level=ERROR source=routes.go:453 msg="embedding generation failed" error="context canceled"
[GIN] 2024/11/08 - 20:21:33 | 500 |   83.252208ms |       127.0.0.1 | POST     "/v1/embeddings"
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
[GIN] 2024/11/08 - 20:21:33 | 500 |   79.253125ms |       127.0.0.1 | POST     "/v1/embeddings"
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
[GIN] 2024/11/08 - 20:21:33 | 500 |   83.123834ms |       127.0.0.1 | POST     "/v1/embeddings"
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
time=2024-11-08T20:21:33.675-05:00 level=ERROR source=routes.go:453 msg="embedding generation failed" error="context canceled"
[GIN] 2024/11/08 - 20:21:33 | 500 |   82.354416ms |       127.0.0.1 | POST     "/v1/embeddings"
Error #01: json: cannot unmarshal object into Go struct field StatusError.error of type string
```

**Comment by kushtrimjunuzi** [comment]
fixed by changing ollama api endpoints:
```
ai_provider_config:
  provider_name: "ollama"
  chat_completion_url: "http://localhost:11434/api/chat"
  chat_completion_model: "deepseek-coder-v2"
  embedding_url: "http://localhost:11434/api/embed"
  embedding_model: "nomic-embed-text"
  temperature: 0.2
  stream: true
  encoding_format: "float"
  threshold: 0
theme: "dracula"
RAG: true

```

**Comment by kushtrimjunuzi** [comment]
fixed by changing ollama api endpoints:
```
ai_provider_config:
  provider_name: "ollama"
  chat_completion_url: "http://localhost:11434/api/chat"
  chat_completion_model: "deepseek-coder-v2"
  embedding_url: "http://localhost:11434/api/embed"
  embedding_model: "nomic-embed-text"
  temperature: 0.2
  stream: true
  encoding_format: "float"
  threshold: 0
theme: "dracula"
RAG: true

```

**Comment by meysamhadeli** [comment]
> fixed by changing ollama api endpoints:
> 
> ```
> ai_provider_config:
>   provider_name: "ollama"
>   chat_completion_url: "http://localhost:11434/api/chat"
>   chat_completion_model: "deepseek-coder-v2"
>   embedding_url: "http://localhost:11434/api/embed"
>   embedding_model: "nomic-embed-text"
>   temperature: 0.2
>   stream: true
>   encoding_format: "float"
>   threshold: 0
> theme: "dracula"
> RAG: true
> ```

@kushtrimjunuzi  Great, I had many refactor in last version, you can check it out the latest version now. :)
